### ISSUE TITLE
Is the API still active?

### ISSUE THREAD

**Issue by vcidst** [ncpierson/soundoftext-web#3]
I see that the repo has a Docs folder but it isn't linked anywhere on the homepage.
https://soundoftext.com/docs#reference

I tried to send a sample request to the API but I get `405 (Method Not Allowed)`. Is the the API still active? I tried from [ReqBin](https://reqbin.com/) and my local machine.

```python
import requests

url = "https://soundoftext.com/sounds"
payload = {"engine": "Google","data": {"text": "Hello, world","voice": "en-US"}}

r = requests.post(url, json=payload)
print(r.text)
```

**Comment by ncpierson** [comment]
Hi, the API is still active. The web app uses the API. The docs are only referenced at the _very_ bottom of the page, under the "API" link.

The url is wrong on line 3. It should be:

```
url = "https://api.soundoftext.com/sounds"
```

Sorry about any confusion! My documentation is not incredibly good.

**Comment by vcidst** [comment]
Oh right, sorry I missed the line in introduction. 

> "The API itself is located at https://api.soundoftext.com and it supports two operations. The first allows you to create a sound, returning an id"
